### ISSUE TITLE
Offset posts

### ISSUE THREAD

**Issue by justiny** [yavisht/WordPress-simple-load-more-posts-using-Vue-and-WP-Rest-API#1]
Thanks for putting this together!

If I was to offset the posts, to grab all posts after 3, for example, how would you go about that?  

Much appreciated!

Edit* Scratch that, I found it: wp-json/wp/v2/posts?per_page=2&offset=3&page=

**Comment by yavisht** [comment]
**More info here:**
https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/
