### ISSUE TITLE
Display post initial posts before clicking to load more

### ISSUE THREAD

**Issue by jekayode** [yavisht/WordPress-simple-load-more-posts-using-Vue-and-WP-Rest-API#3]
Thank you so much for this great work.

I want to get 4 post displayed on page load so that more posts will be loaded when the load more button is clicked.

Thank you

**Comment by yavisht** [comment]
hi @jekayode checkout -> https://github.com/yavisht/WordPress-simple-load-more-posts-using-Vue-and-WP-Rest-API/commit/c7b7287740764b29274f3ef623169923ac189662
